/******************************************************************************
 * Steve Rider - stever@area23.org
 * Grufti - an interactive, service-oriented bot for IRC 
 *
 * cmd.h - the command definitions
 *
 *****************************************************************************/
/* 28 April 97 */

#ifndef CMD_H
#define CMD_H
#include "user.h"

void cmd_rehash();
void cmd_meminfo();
void cmd_say();
void cmd_die();
void cmd_boot();
void cmd_raw();
void cmd_chat();
void cmd_register();
void cmd_setpass();
void cmd_chpass();
void cmd_chusername();
void cmd_addnick();
void cmd_delnick();
void cmd_setfinger();
void cmd_setemail();
void cmd_setwww();
void cmd_setforward();
void cmd_forwardnotes();
void cmd_setother1();
void cmd_setother2();
void cmd_setother3();
void cmd_setother4();
void cmd_setother5();
void cmd_setother6();
void cmd_setother7();
void cmd_setother8();
void cmd_setother9();
void cmd_setother10();
void cmd_setplan1();
void cmd_setplan2();
void cmd_setplan3();
void cmd_setplan4();
void cmd_setplan5();
void cmd_setplan6();
void cmd_setplan_helper();
void cmd_setlocation();
void cmd_done();
void cmd_unregister();
void cmd_motd();
void cmd_resetmotd();
void cmd_pass();
void cmd_exit();
void cmd_addserver();
void cmd_jump();
void cmd_delserver();
void cmd_setvar();
void cmd_servinfo();
void cmd_time();
void cmd_chaninfo();
void cmd_help();
void cmd_showlocations();
void cmd_chlocation();
void cmd_addlocation();
void cmd_dellocation();
void cmd_finger();
void cmd_finger_showallonline();
void cmd_finger_showregistered(userrec *u);
void cmd_finger_showunregistered(userrec *u);
int cmd_finger_helper_makelast(userrec *u, char *outbuf);
void cmd_whois();
void cmd_adduser();
void cmd_notify();
void cmd_deluser();
void cmd_seen();
void cmd_seen_userhost();
void cmd_write();
void cmd_addthisnick();
void cmd_wallnote();
void cmd_note();
void cmd_addnote();
void cmd_showmynote();
void cmd_memo();
void cmd_rn();
void cmd_rn_display(u_long type);
void cmd_dccinfo();
void cmd_savenote();
void cmd_unsavenote();
void cmd_cmdinfo();
void cmd_cmdinfo_long();
void cmd_cmdinfo_short();
void cmd_codesinfo();
void cmd_dn();
void cmd_whoisin();
void cmd_webcatch();
void cmd_clearwebcatch();
void cmd_addgreet();
void cmd_showgreets();
void cmd_showgreets_for_user();
void cmd_delgreet();
void cmd_mode();
void cmd_telnet();
void cmd_maint();
void cmd_version();
void cmd_homepage();
void cmd_uptime();
void cmd_showrtypes();
void cmd_showresponse();
void cmd_showresponses_bytype(rtype *rt);
void cmd_showresponses_byname(rtype *rt, resprec *r);
void cmd_addrespline();
void cmd_delrespmatch();
void cmd_delrespexcept();
void cmd_newresponse();
void cmd_delresponse();
void cmd_delrespline();
void cmd_addrespmatch();
void cmd_newrespmatch();
void cmd_addrespexcept();
void cmd_delhostmask();
void cmd_op();
void cmd_whoami();
void cmd_nn();
void cmd_users();
void cmd_say();
void cmd_act();
void cmd_configinfo();
void cmd_watchlog();
void cmd_files();
void cmd_send();
void cmd_topic();
void cmd_kick();
void cmd_invite();
void cmd_ban();
void cmd_kickban();
void cmd_stat();
void cmd_banlist();
void cmd_addban();
void cmd_delban();
void cmd_voice();
void cmd_leave();
void cmd_join();
void cmd_hush();
void cmd_unhush();
void cmd_backup();
void cmd_showbans();
void cmd_email();
void cmd_url();
void cmd_bday();
void cmd_addevent();
void cmd_delevent();
void cmd_showevents();
void cmd_showevent();
void cmd_seteventname();
void cmd_seteventplace();
void cmd_seteventdates();
void cmd_seteventabout();
void cmd_seteventadmin();
void cmd_attendevent();
void cmd_unattendevent();
void cmd_seteventwhen();
void cmd_seteventcontact();
void cmd_eventnote();
void cmd_setbday();
void cmd_showbdays();
void cmd_helper_showallbdays();
void cmd_helper_showamonthsbdays();
void cmd_showhistory();
void cmd_addhistory();
void cmd_setusernumber();
void cmd_setusercreation();
void cmd_showother();
void cmd_searchresponse();

#endif /* CMD_H */
