# Tmp Makefile until we create one with configure...

tmp:
	@cd ../configure; sh ./configure
	@echo "Ready to compile the bot.  This may take a while..."
	@echo ""
	@make

config:
	@cd ../configure; sh ./configure

dist:
	@echo "Already ready for distribution!"
